/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#8bf9af",
        "on-secondary-container": "#09657f",
        "secondary-fixed-dim": "#89d0ed",
        "tertiary-container": "#00552d",
        "tertiary-fixed-dim": "#6fdc95",
        "inverse-surface": "#2c3134",
        "surface-container-high": "#e4e9ed",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#00210e",
        "on-surface-variant": "#434652",
        "surface-container-lowest": "#ffffff",
        background: "#f6fafe",
        "surface-container": "#eaeef2",
        secondary: "#0c6780",
        "secondary-fixed": "#baeaff",
        error: "#ba1a1a",
        "surface-variant": "#dfe3e7",
        "on-primary-container": "#9db6ff",
        "inverse-primary": "#b2c5ff",
        "error-container": "#ffdad6",
        "surface-bright": "#f6fafe",
        surface: "#f6fafe",
        "on-primary-fixed": "#001848",
        "on-primary": "#ffffff",
        primary: "#002d77",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary-fixed-variant": "#0b419d",
        "surface-container-low": "#f0f4f8",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#001f29",
        "on-tertiary-container": "#60ce88",
        tertiary: "#003b1e",
        "secondary-container": "#9ae1ff",
        "on-tertiary-fixed-variant": "#00522b",
        "primary-fixed": "#dae2ff",
        "inverse-on-surface": "#edf1f5",
        "surface-tint": "#305ab6",
        "on-secondary-fixed-variant": "#004d62",
        "primary-container": "#10439f",
        "outline-variant": "#c4c6d4",
        "surface-container-highest": "#dfe3e7",
        outline: "#747783",
        "surface-dim": "#d6dade",
        "on-surface": "#171c1f",
        "on-background": "#171c1f",
        "on-error": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};